Importig libraries

In [1]:
import pandas as pd
import numpy as np

Loading the datset into python

In [2]:
data = pd.read_excel(r'C:\Users\Sanza Vijin\Downloads\iris (2).xls')

In [3]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

### Preprocessing

In [4]:
data.shape

(150, 5)

In [5]:
data.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
fill_data = data.fillna(method ='ffill')

In [8]:
fill_data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [29]:
x= fill_data.drop(['Classification'],axis=1)
y =fill_data['Classification']

Splitting the data

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [12]:
x_train.shape

(105, 4)

In [13]:
y_train.shape

(105, 3)

In [14]:
x_test.shape

(45, 4)

In [15]:
y_test.shape

(45, 3)

#### Find out which classification model gives the best result to predict iris species

### Random Forests

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf = RandomForestClassifier()

In [18]:
rf.fit(x_train,y_train) #training the model
y_pred = rf.predict(x_test) #prediction using test

In [19]:
from sklearn.metrics import f1_score,confusion_matrix

In [20]:
confusion_matrix(y_test.values.argmax(axis=1), y_pred.argmax(axis=1))

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [21]:
f1_score(y_test,y_pred,average='micro')

1.0

RandomForest classfier gives 100% accuracy

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

### Logistic Regression

In [32]:
log_model=LogisticRegression()

In [33]:
log_model.fit(x_train,y_train)
y_pred=log_model.predict(x_test)

In [34]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [35]:
print('Confusion Matrix\n',confusion_matrix(y_test,y_pred))

Confusion Matrix
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [36]:
print(' Classification Report\n',classification_report(y_test,y_pred))

 Classification Report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



logistic regression is giving 100% accuracy

### Decision Tree

In [37]:
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train,y_train)
y_pred=dt_model.predict(x_test)
print('Confusion Matrix\n',confusion_matrix(y_test,y_pred))
print(' Classification Report\n',classification_report(y_test,y_pred))

Confusion Matrix
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
 Classification Report
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



Decision Tree is giving 100 percent accuracy